# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\xde\x01\n\rStreamRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\nscreenshot\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0cscreen_width\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x1a\n\rscreen_height\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x13\n\x0bhardware_id\x18\x05 \x01(\t\x12\x17\n\nsession_id\x18\x06 \x01(\tH\x03\x88\x01\x01\x42\r\n\x0b_screenshotB\x0f\n\r_screen_widthB\x10\n\x0e_screen_heightB\r\n\x0b_session_id\"\x8f\x01\n\x0eStreamResponse\x12\x14\n\ntext_chunk\x18\x01 \x01(\tH\x00\x12,\n\x0b\x61udio_chunk\x18\x02 \x01(\x0b\x32\x15.streaming.AudioChunkH\x00\x12\x15\n\x0b\x65nd_message\x18\x03 \x01(\tH\x00\x12\x17\n\rerror_message\x18\x04 \x01(\tH\x00\x42\t\n\x07\x63ontent\">\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x05\"\'\n\x10InterruptRequest\x12\x13\n\x0bhardware_id\x18\x01 \x01(\t\"S\n\x11InterruptResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x14interrupted_sessions\x18\x02 \x03(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"L\n\x13WelcomeAudioRequest\x12\x13\n\x0bhardware_id\x18\x01 \x01(\t\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"\x7f\n\x14WelcomeAudioResponse\x12,\n\x0b\x61udio_chunk\x18\x01 \x01(\x0b\x32\x15.streaming.AudioChunkH\x00\x12\x15\n\x0b\x65nd_message\x18\x02 \x01(\tH\x00\x12\x17\n\rerror_message\x18\x03 \x01(\tH\x00\x42\t\n\x07\x63ontent2\x82\x02\n\x10StreamingService\x12\x44\n\x0bStreamAudio\x12\x18.streaming.StreamRequest\x1a\x19.streaming.StreamResponse0\x01\x12M\n\x10InterruptSession\x12\x1b.streaming.InterruptRequest\x1a\x1c.streaming.InterruptResponse\x12Y\n\x14GenerateWelcomeAudio\x12\x1e.streaming.WelcomeAudioRequest\x1a\x1f.streaming.WelcomeAudioResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=31
  _globals['_STREAMREQUEST']._serialized_end=253
  _globals['_STREAMRESPONSE']._serialized_start=256
  _globals['_STREAMRESPONSE']._serialized_end=399
  _globals['_AUDIOCHUNK']._serialized_start=401
  _globals['_AUDIOCHUNK']._serialized_end=463
  _globals['_INTERRUPTREQUEST']._serialized_start=465
  _globals['_INTERRUPTREQUEST']._serialized_end=504
  _globals['_INTERRUPTRESPONSE']._serialized_start=506
  _globals['_INTERRUPTRESPONSE']._serialized_end=589
  _globals['_WELCOMEAUDIOREQUEST']._serialized_start=591
  _globals['_WELCOMEAUDIOREQUEST']._serialized_end=667
  _globals['_WELCOMEAUDIORESPONSE']._serialized_start=669
  _globals['_WELCOMEAUDIORESPONSE']._serialized_end=796
  _globals['_STREAMINGSERVICE']._serialized_start=799
  _globals['_STREAMINGSERVICE']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
