from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Any, Optional, Tuple


@dataclass(frozen=True)
class GoalStackGateCase:
    case_id: str
    tier: str
    transition_type: str
    category: str
    prompt_style: str
    paired: bool
    owner_focus: Tuple[str, ...]
    summary: str
    live_request: Optional[str] = None
    live_expected_route: Optional[str] = None
    live_expected_command: Optional[str] = None
    live_expected_text_contains: Tuple[str, ...] = ()
    live_expected_goal_state: Optional[str] = None
    live_hardware_id: Optional[str] = None
    live_seed_turns: Tuple[Tuple[str, str], ...] = ()
    classifier_request: Optional[str] = None
    classifier_expected_route: Optional[str] = None
    classifier_runtime_current_goal: Optional[str] = None
    classifier_runtime_short_term: Optional[str] = None
    classifier_has_image: bool = False
    memory_prompt: Optional[str] = None
    memory_response: Optional[str] = None
    memory_current_goal: Optional[str] = None
    memory_expected_goal: Optional[str] = None
    memory_analyzer_long: str = ""
    memory_expected_long: str = ""
    deterministic_request: Optional[str] = None
    deterministic_setup: Tuple[str, ...] = ()
    deterministic_expected_category: Optional[str] = None
    deterministic_expected_route: Optional[str] = None
    deterministic_expected_command: Optional[str] = None
    deterministic_expected_args: Optional[dict[str, Any]] = None
    deterministic_expected_text: Optional[str] = None
    deterministic_seed_goal: Optional[str] = None
    deterministic_seed_turn: Optional[str] = None

    @property
    def interaction_shape(self) -> str:
        if self.transition_type == "cancel":
            return "cancel"
        if self.transition_type == "replace":
            return "pivot"
        if self.transition_type in {"pronoun_continuation", "short_continuation", "continuation_completion"}:
            return "follow_up"
        if self.transition_type == "no_task":
            return "non_task"
        return "direct"

    @property
    def noise_profile(self) -> str:
        if self.prompt_style == "dirty":
            return "stt_like"
        if self.transition_type == "pronoun_continuation":
            return "pronoun"
        if self.transition_type == "short_continuation":
            return "fragment"
        return "clean"

    @property
    def slot_pattern(self) -> str:
        if self.case_id in {"g01_messages_start", "g03_whatsapp_start"}:
            return "missing_message"
        if self.case_id in {"g06_browser_followup_short", "g08_search_followup_topic", "g11_system_followup_target"}:
            return "known_slot_reuse"
        if self.case_id == "g10_system_clarify_start":
            return "missing_app"
        if self.case_id in {"g17_dirty_messages_recoverable", "g18_dirty_browser_recoverable", "g19_dirty_search_recoverable", "g20_dirty_describe_recoverable"}:
            return "noisy_recovery"
        if self.category == "none":
            return "none"
        return "full_payload"

    @property
    def outcome_shape(self) -> str:
        if self.transition_type == "cancel":
            return "cancel"
        if self.category in {"google_search", "describe", "capability", "none"} and self.live_expected_command is None:
            return "answer"
        if self.live_expected_command is None and self.live_expected_goal_state in {"set", "keep"}:
            return "clarify"
        if self.live_expected_command is not None:
            return "execute"
        return "answer"


def build_goal_stack_gate_matrix_rows(cases: Optional[Tuple["GoalStackGateCase", ...]] = None) -> tuple[dict[str, Any], ...]:
    selected_cases = cases or CANONICAL_20_CASE_GATE
    return tuple(
        {
            "case_id": case.case_id,
            "tier": case.tier,
            "transition_type": case.transition_type,
            "category": case.category,
            "prompt_style": case.prompt_style,
            "interaction_shape": case.interaction_shape,
            "noise_profile": case.noise_profile,
            "slot_pattern": case.slot_pattern,
            "outcome_shape": case.outcome_shape,
            "paired": case.paired,
            "owner_focus": case.owner_focus,
            "summary": case.summary,
        }
        for case in selected_cases
    )


CANONICAL_20_CASE_GATE: tuple[GoalStackGateCase, ...] = (
    GoalStackGateCase(
        "g01_messages_start",
        "core",
        "new_task",
        "messages",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Start Messages clarification chain with explicit recipient.",
        live_request="Drop Sophia a note",
        live_expected_route="messages",
        live_expected_text_contains=("Sophia",),
        live_expected_goal_state="set",
        live_hardware_id="live-g01-messages",
        classifier_request="drop Sophia a note",
        classifier_expected_route="messages",
        memory_prompt="Drop Sophia a note",
        memory_response="What message would you like to send to Sophia?",
        memory_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        memory_expected_goal="User wants to send a message to Sophia. Missing detail: message text.",
        deterministic_request="Drop Sophia a note",
        deterministic_expected_category="messages",
        deterministic_expected_route="messages",
        deterministic_expected_text="What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g02_messages_followup_pronoun",
        "core",
        "pronoun_continuation",
        "messages",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Continue active Messages chain with pronoun payload reuse.",
        live_request="Tell her I'm running behind",
        live_expected_route="messages",
        live_expected_command="send_message",
        live_expected_text_contains=("Sending", "Sophia"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g01-messages",
        classifier_request="tell her i'm running behind",
        classifier_expected_route="messages",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:32:39 UTC\nUSER: I need to send Sophia a message\nASSISTANT: What message would you like to send to Sophia?",
        memory_prompt="Tell her I'm running behind",
        memory_response="Sending your message to Sophia.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="Tell her I'm running behind",
        deterministic_expected_category="messages",
        deterministic_expected_route="messages",
        deterministic_expected_command="send_message",
        deterministic_expected_args={"contact": "Sophia", "message": "I'm running behind"},
        deterministic_expected_text="Sending your message to Sophia.",
        deterministic_seed_goal="User wants to send a message to Sophia. Missing detail: message text.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:23:00 UTC\nUSER: I need to send Sophia a message\nASSISTANT: What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g03_whatsapp_start",
        "core",
        "new_task",
        "whatsapp",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Start WhatsApp clarification chain.",
        live_request="Message Mom on WhatsApp",
        live_expected_route="whatsapp",
        live_expected_text_contains=("Mom",),
        live_expected_goal_state="set",
        live_hardware_id="live-g03-whatsapp",
        classifier_request="message Mom on WhatsApp",
        classifier_expected_route="whatsapp",
        memory_prompt="Message Mom on WhatsApp",
        memory_response="What message do you want to send to Mom?",
        memory_current_goal="User wants to send a WhatsApp message to Mom. Missing detail: message text.",
        memory_expected_goal="User wants to send a WhatsApp message to Mom. Missing detail: message text.",
        deterministic_request="Message Mom on WhatsApp",
        deterministic_expected_category="whatsapp",
        deterministic_expected_route="whatsapp",
        deterministic_expected_text="What message do you want to send to Mom?",
    ),
    GoalStackGateCase(
        "g04_whatsapp_followup",
        "core",
        "continuation_completion",
        "whatsapp",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Finish WhatsApp chain with known contact reuse.",
        live_request="Say I made it home",
        live_expected_route="whatsapp",
        live_expected_command="send_whatsapp_message",
        live_expected_text_contains=("Mom",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g03-whatsapp",
        classifier_request="continue",
        classifier_expected_route="whatsapp",
        classifier_runtime_current_goal="User wants to send a WhatsApp message to Mom. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:40:00 UTC\nUSER: send a WhatsApp message to Mom\nASSISTANT: What message do you want to send to Mom?",
        memory_prompt="Say I made it home",
        memory_response="Sending your WhatsApp message to Mom.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="Say I made it home",
        deterministic_expected_category="whatsapp",
        deterministic_expected_route="whatsapp",
        deterministic_expected_text="Sending your WhatsApp message to Mom.",
        deterministic_seed_goal="User wants to send a WhatsApp message to Mom. Missing detail: message text.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:28:00 UTC\nUSER: send a WhatsApp message to Mom\nASSISTANT: What message do you want to send to Mom?",
    ),
    GoalStackGateCase(
        "g05_browser_direct",
        "core",
        "same_turn_completion",
        "browser",
        "clean",
        False,
        ("memory", "classifier", "generator", "live"),
        "Direct browser action without clarification.",
        live_request="Pull up YouTube and spin some jazz",
        live_expected_route="browser",
        live_expected_command="browser_use",
        live_expected_text_contains=("YouTube",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g05-browser",
        classifier_request="pull up YouTube and spin some jazz",
        classifier_expected_route="browser",
        memory_prompt="Pull up YouTube and spin some jazz",
        memory_response="Opening YouTube and playing jazz.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="Pull up YouTube and spin some jazz",
        deterministic_expected_category="browser",
        deterministic_expected_route="browser",
        deterministic_expected_command="browser_use",
        deterministic_expected_args={"task": "pull up youtube and spin some jazz"},
        deterministic_expected_text="Opening YouTube and spinning some jazz.",
    ),
    GoalStackGateCase(
        "g06_browser_followup_short",
        "core",
        "short_continuation",
        "browser",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Continue browser chain with short target phrase.",
        live_request="swap it over to sleep sounds",
        live_expected_route="browser",
        live_expected_command="browser_use",
        live_expected_text_contains=("sleep",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g06-browser-followup",
        live_seed_turns=(("Open YouTube and find something for me", "What should I find on YouTube?"),),
        classifier_request="swap it over to rain sounds",
        classifier_expected_route="browser",
        classifier_runtime_current_goal="User wants to search YouTube. Missing detail: search query.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:35:00 UTC\nUSER: Open YouTube and find something for me\nASSISTANT: What should I find on YouTube?",
        memory_prompt="Open YouTube and find something for me",
        memory_response="What should I find on YouTube?",
        memory_current_goal="User wants to search YouTube. Missing detail: search query.",
        memory_expected_goal="User wants to search YouTube. Missing detail: search query.",
        deterministic_request="make it sleep music instead",
        deterministic_expected_category="browser",
        deterministic_expected_route="browser",
        deterministic_expected_command="browser_use",
        deterministic_expected_args={"task": "open youtube and find sleep music"},
        deterministic_expected_text="Opening YouTube to find sleep music.",
        deterministic_seed_goal="User wants to search YouTube. Missing detail: search query.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:22:00 UTC\nUSER: Open YouTube and find something for me\nASSISTANT: What should I find on YouTube?",
    ),
    GoalStackGateCase(
        "g07_search_direct",
        "core",
        "same_turn_completion",
        "google_search",
        "clean",
        False,
        ("memory", "classifier", "generator", "live"),
        "Direct factual search answered in the same turn.",
        live_request="Catch me up on world news",
        live_expected_route="google_search",
        live_expected_text_contains=("world", "news"),
        live_expected_goal_state="empty",
        live_hardware_id="live-g07-search",
        classifier_request="catch me up on world news",
        classifier_expected_route="google_search",
        memory_prompt="Catch me up on world news",
        memory_response="Here are the latest world news headlines.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="Catch me up on world news",
        deterministic_expected_category="google_search",
        deterministic_expected_route="google_search",
        deterministic_expected_text="Here are the latest world news headlines.",
        deterministic_seed_goal="User wants news. Missing detail: topic.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:24:00 UTC\nUSER: find news\nASSISTANT: What kind of news do you want?",
    ),
    GoalStackGateCase(
        "g08_search_followup_topic",
        "core",
        "continuation_completion",
        "google_search",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Resolve search topic after clarification.",
        live_request="global affairs",
        live_expected_route="google_search",
        live_expected_text_contains=("global", "affairs", "headlines"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g08-search-followup",
        live_seed_turns=(("Find some news for me", "What kind of news do you want?"),),
        classifier_request="global affairs",
        classifier_expected_route="google_search",
        classifier_runtime_current_goal="User wants news. Missing detail: topic.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:36:00 UTC\nUSER: Find some news for me\nASSISTANT: What kind of news do you want?",
        memory_prompt="Find some news for me",
        memory_response="What kind of news do you want?",
        memory_current_goal="User wants news. Missing detail: topic.",
        memory_expected_goal="User wants news. Missing detail: topic.",
        deterministic_request="global affairs",
        deterministic_expected_category="google_search",
        deterministic_expected_route="google_search",
        deterministic_expected_text="Here are the latest world news headlines.",
    ),
    GoalStackGateCase(
        "g09_system_direct",
        "core",
        "same_turn_completion",
        "system_control",
        "clean",
        False,
        ("memory", "classifier", "generator", "live"),
        "Open desktop app directly.",
        live_request="Launch Safari for me",
        live_expected_route="system_control",
        live_expected_command="open_app",
        live_expected_text_contains=("Safari",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g09-system",
        classifier_request="launch Safari for me",
        classifier_expected_route="system_control",
        memory_prompt="Launch Safari for me",
        memory_response="Opening Safari.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="Launch Safari for me",
        deterministic_expected_category="system_control",
        deterministic_expected_route="system_control",
        deterministic_expected_command="open_app",
        deterministic_expected_args={"app_name": "Safari"},
        deterministic_expected_text="Opening Safari.",
    ),
    GoalStackGateCase(
        "g10_system_clarify_start",
        "core",
        "new_task",
        "system_control",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Start app-open clarification when app name is missing.",
        live_request="Open some app",
        live_expected_route="system_control",
        live_expected_text_contains=("open",),
        live_expected_goal_state="set",
        live_hardware_id="live-g10-system-clarify",
        classifier_request="open some app",
        classifier_expected_route="none",
        memory_prompt="Open some app",
        memory_response="What app do you want to open?",
        memory_current_goal="User wants to open an app. Missing detail: app name.",
        memory_expected_goal="User wants to open an app. Missing detail: app name.",
        deterministic_request="Open some app",
        deterministic_expected_category="none",
        deterministic_expected_route="none",
        deterministic_expected_text="What do you want to open?",
    ),
    GoalStackGateCase(
        "g11_system_followup_target",
        "core",
        "continuation_completion",
        "system_control",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Resolve missing app slot and execute.",
        live_request="Safari browser",
        live_expected_route="system_control",
        live_expected_command="open_app",
        live_expected_text_contains=("Safari",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g10-system-clarify",
        classifier_request="Safari browser",
        classifier_expected_route="system_control",
        classifier_runtime_current_goal="User wants to open an app. Missing detail: app name.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:37:00 UTC\nUSER: Open something for me\nASSISTANT: What app do you want to open?",
        memory_prompt="No, open Safari instead",
        memory_response="Opening Safari.",
        memory_current_goal="User wants to open Safari.",
        memory_expected_goal="User wants to open Safari.",
        deterministic_request="Safari please",
        deterministic_setup=("Open something for me",),
        deterministic_expected_category="system_control",
        deterministic_expected_route="system_control",
        deterministic_expected_command="open_app",
        deterministic_expected_args={"app_name": "Safari"},
        deterministic_expected_text="Opening Safari.",
    ),
    GoalStackGateCase(
        "g12_cancel_old_task",
        "core",
        "cancel",
        "none",
        "clean",
        True,
        ("memory", "classifier", "live"),
        "Cancel an active task without starting a new one.",
        live_request="Forget that task",
        live_expected_route="none",
        live_expected_text_contains=("okay",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g12-cancel",
        live_seed_turns=(("Send a message to Sophia", "What message would you like to send to Sophia?"),),
        classifier_request="forget that task",
        classifier_expected_route="none",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:10:00 UTC\nUSER: send a message to Sophia\nASSISTANT: What message would you like to send to Sophia?",
        memory_prompt="Forget that task",
        memory_response="Okay, I will not continue that task.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="Forget that task",
        deterministic_setup=("I need to send Sophia a message",),
        deterministic_expected_category="none",
        deterministic_expected_route="none",
        deterministic_expected_text="Okay, I will not continue that task.",
    ),
    GoalStackGateCase(
        "g13_replace_message_to_app",
        "core",
        "replace",
        "system_control",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Replace active messaging task with app open.",
        live_request="Scrap that, launch Safari",
        live_expected_route="system_control",
        live_expected_command="open_app",
        live_expected_text_contains=("Opening", "Safari"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g13-replace-app",
        live_seed_turns=(("I need to send Sophia a message", "What message would you like to send to Sophia?"),),
        classifier_request="scrap that, launch Safari",
        classifier_expected_route="system_control",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:12:00 UTC\nUSER: I need to send Sophia a message\nASSISTANT: What message would you like to send to Sophia?",
        memory_prompt="Scrap that, launch Safari",
        memory_response="Opening Safari.",
        memory_current_goal="User wants to open Safari.",
        memory_expected_goal="User wants to open Safari.",
        deterministic_request="Scrap that, launch Safari",
        deterministic_setup=("I need to send Sophia a message",),
        deterministic_expected_category="system_control",
        deterministic_expected_route="system_control",
        deterministic_expected_command="open_app",
        deterministic_expected_args={"app_name": "Safari"},
        deterministic_expected_text="Opening Safari.",
    ),
    GoalStackGateCase(
        "g14_replace_browser_to_message",
        "core",
        "replace",
        "messages",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Replace active browser task with Messages task.",
        live_request="Skip that, text Sophia",
        live_expected_route="messages",
        live_expected_text_contains=("Sophia",),
        live_expected_goal_state="set",
        live_hardware_id="live-g14-replace-message",
        live_seed_turns=(("Open YouTube and find", "What should I find on YouTube?"),),
        classifier_request="skip that, text Sophia",
        classifier_expected_route="messages",
        classifier_runtime_current_goal="User wants to search YouTube. Missing detail: search query.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:16:00 UTC\nUSER: open YouTube and find\nASSISTANT: What should I find on YouTube?",
        memory_prompt="No, never mind",
        memory_response="Okay, I will not continue that task.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="Actually, message Sophia instead",
        deterministic_setup=("open YouTube and find",),
        deterministic_expected_category="messages",
        deterministic_expected_route="messages",
        deterministic_expected_text="What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g15_casual_none",
        "core",
        "no_task",
        "none",
        "clean",
        False,
        ("memory", "classifier", "live"),
        "Ordinary conversation must not create a goal.",
        live_request="How've you been?",
        live_expected_route="none",
        live_expected_text_contains=("doing",),
        live_expected_goal_state="empty",
        live_hardware_id="live-g15-casual",
        classifier_request="how've you been",
        classifier_expected_route="none",
        memory_prompt="How've you been?",
        memory_response="I'm doing well, thank you.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="How've you been?",
        deterministic_expected_category="none",
        deterministic_expected_route="none",
        deterministic_expected_text="I am doing well, thanks for asking.",
    ),
    GoalStackGateCase(
        "g16_capability_direct",
        "core",
        "no_task",
        "capability",
        "clean",
        False,
        ("memory", "classifier", "live"),
        "Capability request must stay outside executable lifecycle.",
        live_request="What are you able to do?",
        live_expected_route="capability",
        live_expected_text_contains=("help",),
        live_expected_goal_state="empty",
        live_hardware_id="live-g16-capability",
        classifier_request="what are you able to do",
        classifier_expected_route="capability",
        memory_prompt="What are you able to do?",
        memory_response="I can help with messages, apps, browsing, and search.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="What are you able to do",
        deterministic_expected_category="capability",
        deterministic_expected_route="capability",
        deterministic_expected_text="I can help with apps, browser, messages, search, screen description, and device actions.",
    ),
    GoalStackGateCase(
        "g17_dirty_messages_recoverable",
        "rotatable",
        "pronoun_continuation",
        "messages",
        "dirty",
        True,
        ("classifier", "generator", "live"),
        "Recover noisy pronoun follow-up in an active Messages chain.",
        live_request="msg her im downstairs now",
        live_expected_route="messages",
        live_expected_command="send_message",
        live_expected_text_contains=("Sending", "Sophia"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g17-dirty-messages",
        live_seed_turns=(("I need to send Sophia a message", "What message would you like to send to Sophia?"),),
        classifier_request="msg her im downstairs now",
        classifier_expected_route="messages",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:18:00 UTC\nUSER: I need to send Sophia a message\nASSISTANT: What message would you like to send to Sophia?",
        memory_prompt="Thank you",
        memory_response="You're welcome.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="msg her im downstairs now",
        deterministic_expected_category="messages",
        deterministic_expected_route="messages",
        deterministic_expected_command="send_message",
        deterministic_expected_args={"contact": "Sophia", "message": "im downstairs"},
        deterministic_expected_text="Sending your message to Sophia.",
        deterministic_seed_goal="User wants to send a message to Sophia. Missing detail: message text.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:18:00 UTC\nUSER: I need to send Sophia a message\nASSISTANT: What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g18_dirty_browser_recoverable",
        "rotatable",
        "short_continuation",
        "browser",
        "dirty",
        True,
        ("classifier", "generator", "live"),
        "Recover noisy short browser follow-up after a YouTube clarification chain.",
        live_request="yt ambient rain swap",
        live_expected_route="browser",
        live_expected_command="browser_use",
        live_expected_text_contains=("YouTube", "ambient", "rain"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g18-dirty-browser-followup",
        live_seed_turns=(("Open YouTube and find", "What should I find on YouTube?"),),
        classifier_request="yt ambient rain swap",
        classifier_expected_route="browser",
        classifier_runtime_current_goal="User wants to search YouTube. Missing detail: search query.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:20:00 UTC\nUSER: open YouTube and find\nASSISTANT: What should I find on YouTube?",
        memory_prompt="No, I just want to know how are you doing",
        memory_response="I am doing well, thanks for asking.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="yt ambient rain swap",
        deterministic_expected_category="browser",
        deterministic_expected_route="browser",
        deterministic_expected_command="browser_use",
        deterministic_expected_args={"task": "open youtube and play ambient rain"},
        deterministic_expected_text="Opening YouTube and playing ambient rain.",
        deterministic_seed_goal="User wants to search YouTube. Missing detail: search query.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:20:00 UTC\nUSER: open YouTube and find\nASSISTANT: What should I find on YouTube?",
    ),
    GoalStackGateCase(
        "g19_dirty_search_recoverable",
        "rotatable",
        "replace",
        "google_search",
        "dirty",
        True,
        ("classifier", "generator", "live"),
        "Recover noisy replace-to-search pivot from an active messaging task.",
        live_request="actually global headlines instead",
        live_expected_route="google_search",
        live_expected_text_contains=("global", "headlines"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g19-dirty-search-pivot",
        live_seed_turns=(("I need to send Sophia a message", "What message would you like to send to Sophia?"),),
        classifier_request="actually global headlines instead",
        classifier_expected_route="google_search",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:21:00 UTC\nUSER: I need to send Sophia a message\nASSISTANT: What message would you like to send to Sophia?",
        memory_prompt="Send a message",
        memory_response="Who do you want to send it to?",
        memory_current_goal="User wants to send a message. Missing detail: recipient.",
        memory_expected_goal="User wants to send a message. Missing detail: recipient.",
        deterministic_request="actually global headlines instead",
        deterministic_expected_category="google_search",
        deterministic_expected_route="google_search",
        deterministic_expected_text="Here are the latest global headlines.",
        deterministic_seed_goal="User wants to send a message to Sophia. Missing detail: message text.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:21:00 UTC\nUSER: I need to send Sophia a message\nASSISTANT: What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g20_dirty_describe_recoverable",
        "rotatable",
        "same_turn_completion",
        "describe",
        "dirty",
        False,
        ("classifier", "generator", "live"),
        "Recover noisy describe request and stay on describe route.",
        live_request="what's on screen atm",
        live_expected_route="describe",
        live_expected_text_contains=("screen",),
        live_expected_goal_state="empty",
        live_hardware_id="live-g20-dirty-describe",
        classifier_request="",
        classifier_expected_route="describe",
        classifier_has_image=True,
        memory_prompt="What did I ask before?",
        memory_response="You asked me to send a message earlier.",
        memory_current_goal="",
        memory_expected_goal="",
        deterministic_request="what's on screen atm",
        deterministic_expected_category="describe",
        deterministic_expected_route="describe",
        deterministic_expected_text="Describing your screen.",
    ),
)


SUPPLEMENTAL_20_CASE_GATE: tuple[GoalStackGateCase, ...] = (
    replace(
        CANONICAL_20_CASE_GATE[0],
        case_id="s01_messages_start",
        tier="supplemental",
        summary="Alternate Messages start phrasing with softer helper wording.",
        live_request="I wanna ping Sophia",
        live_hardware_id="live-s01-messages",
        classifier_request="i wanna ping Sophia",
        memory_prompt="I wanna ping Sophia",
        deterministic_request="I wanna ping Sophia",
    ),
    replace(
        CANONICAL_20_CASE_GATE[1],
        case_id="s02_messages_followup_pronoun",
        tier="supplemental",
        summary="Alternate Messages pronoun follow-up with natural timing detail.",
        live_request="Tell her traffic's bad",
        live_hardware_id="live-s01-messages",
        classifier_request="tell her traffic's bad",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:32:39 UTC\nUSER: I wanna ping Sophia\nASSISTANT: What message would you like to send to Sophia?",
        memory_prompt="Tell her traffic's bad",
        deterministic_request="Tell her traffic's bad",
        deterministic_expected_args={"contact": "Sophia", "message": "traffic's bad"},
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:23:00 UTC\nUSER: I wanna ping Sophia\nASSISTANT: What message would you like to send to Sophia?",
    ),
    replace(
        CANONICAL_20_CASE_GATE[2],
        case_id="s03_whatsapp_start",
        tier="supplemental",
        summary="Alternate WhatsApp start phrasing.",
        live_request="WhatsApp Mom",
        live_hardware_id="live-s03-whatsapp",
        classifier_request="whatsapp Mom",
        memory_prompt="WhatsApp Mom",
        deterministic_request="WhatsApp Mom",
    ),
    replace(
        CANONICAL_20_CASE_GATE[3],
        case_id="s04_whatsapp_followup",
        tier="supplemental",
        summary="Alternate WhatsApp completion phrasing.",
        live_request="Tell Mom I'm outside",
        live_hardware_id="live-s03-whatsapp",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:40:00 UTC\nUSER: WhatsApp Mom\nASSISTANT: What message do you want to send to Mom?",
        memory_prompt="Tell Mom I'm outside",
        deterministic_request="Tell Mom I'm outside",
        deterministic_expected_args={"contact": "Mom", "message": "I'm outside"},
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:28:00 UTC\nUSER: WhatsApp Mom\nASSISTANT: What message do you want to send to Mom?",
    ),
    replace(
        CANONICAL_20_CASE_GATE[4],
        case_id="s05_browser_direct",
        tier="supplemental",
        summary="Alternate browser direct request with softer wording.",
        live_request="Open YouTube and start jazz",
        live_hardware_id="live-s05-browser",
        classifier_request="open YouTube and start jazz",
        memory_prompt="Open YouTube and start jazz",
        deterministic_request="Open YouTube and start jazz",
        deterministic_expected_args={"task": "open youtube and start jazz"},
        deterministic_expected_text="Opening YouTube and starting jazz.",
    ),
    replace(
        CANONICAL_20_CASE_GATE[5],
        case_id="s06_browser_followup_short",
        tier="supplemental",
        summary="Alternate browser short follow-up with softer switch wording.",
        live_request="change it to sleep tracks",
        live_hardware_id="live-s06-browser-followup",
        live_seed_turns=(("Open YouTube and find something for me", "What should I find on YouTube?"),),
        classifier_request="change it to rain tracks",
        deterministic_request="change it to sleep tracks",
        deterministic_expected_args={"task": "open youtube and find sleep tracks"},
        deterministic_expected_text="Opening YouTube to find sleep tracks.",
    ),
    replace(
        CANONICAL_20_CASE_GATE[6],
        case_id="s07_search_direct",
        tier="supplemental",
        summary="Alternate direct search phrasing with explicit request verb.",
        live_request="Show me current world news",
        live_hardware_id="live-s07-search",
        classifier_request="show me current world news",
        memory_prompt="Show me current world news",
        deterministic_request="Show me current world news",
        deterministic_expected_text="Here are the latest world news headlines.",
    ),
    replace(
        CANONICAL_20_CASE_GATE[7],
        case_id="s08_search_followup_topic",
        tier="supplemental",
        summary="Alternate search topic follow-up using noun phrase.",
        live_request="europe headlines",
        live_hardware_id="live-s08-search-followup",
        live_seed_turns=(("Find some news for me", "What kind of news do you want?"),),
        live_expected_text_contains=("europe", "headlines"),
        classifier_request="europe headlines",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:36:00 UTC\nUSER: Find some news for me\nASSISTANT: What kind of news do you want?",
        deterministic_request="europe headlines",
        deterministic_expected_text="Here are the latest Europe headlines.",
    ),
    replace(
        CANONICAL_20_CASE_GATE[8],
        case_id="s09_system_direct",
        tier="supplemental",
        summary="Alternate direct system-control phrasing.",
        live_request="Start Safari",
        live_hardware_id="live-s09-system",
        classifier_request="start Safari",
        memory_prompt="Start Safari",
        deterministic_request="Start Safari",
    ),
    replace(
        CANONICAL_20_CASE_GATE[9],
        case_id="s10_system_clarify_start",
        tier="supplemental",
        summary="Alternate app clarification start phrasing.",
        live_request="Open an application",
        live_hardware_id="live-s10-system-clarify",
        classifier_request="open an application",
        memory_prompt="Open an application",
        deterministic_request="Open an application",
        deterministic_expected_text="What do you want to open?",
    ),
    replace(
        CANONICAL_20_CASE_GATE[10],
        case_id="s11_system_followup_target",
        tier="supplemental",
        summary="Alternate app target follow-up phrasing.",
        live_request="Safari one",
        live_hardware_id="live-s10-system-clarify",
        classifier_request="Safari one",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:37:00 UTC\nUSER: Open a program for me\nASSISTANT: What app do you want to open?",
        deterministic_request="Safari one",
        deterministic_setup=("Open a program for me",),
        deterministic_expected_text="Opening Safari.",
    ),
    replace(
        CANONICAL_20_CASE_GATE[11],
        case_id="s12_cancel_old_task",
        tier="supplemental",
        summary="Alternate cancel phrasing.",
        live_request="Cancel that",
        classifier_request="cancel that",
        memory_prompt="Cancel that",
        deterministic_request="Cancel that",
        deterministic_setup=("I wanna ping Sophia",),
        live_seed_turns=(("I wanna ping Sophia", "What message would you like to send to Sophia?"),),
    ),
    replace(
        CANONICAL_20_CASE_GATE[12],
        case_id="s13_replace_message_to_app",
        tier="supplemental",
        summary="Alternate replace-to-app phrasing.",
        live_request="Actually start Safari",
        live_hardware_id="live-s13-replace-app",
        live_seed_turns=(("I wanna ping Sophia", "What message would you like to send to Sophia?"),),
        classifier_request="actually start Safari",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:12:00 UTC\nUSER: I wanna ping Sophia\nASSISTANT: What message would you like to send to Sophia?",
        memory_prompt="Actually start Safari",
        deterministic_request="Actually start Safari",
        deterministic_setup=("I wanna ping Sophia",),
    ),
    replace(
        CANONICAL_20_CASE_GATE[13],
        case_id="s14_replace_browser_to_message",
        tier="supplemental",
        summary="Alternate replace-to-message phrasing.",
        live_request="Actually ping Sophia",
        live_hardware_id="live-s14-replace-message",
        classifier_request="actually ping Sophia",
        deterministic_request="Actually ping Sophia",
    ),
    replace(
        CANONICAL_20_CASE_GATE[14],
        case_id="s15_chat_smalltalk",
        tier="supplemental",
        summary="Alternate ordinary conversation phrasing.",
        live_request="You alright today?",
        classifier_request="you alright today",
        memory_prompt="You alright today?",
        deterministic_request="You alright today?",
    ),
    replace(
        CANONICAL_20_CASE_GATE[15],
        case_id="s16_capability",
        tier="supplemental",
        summary="Alternate capability wording.",
        live_request="What can you handle?",
        classifier_request="what can you handle",
        memory_prompt="What can you handle?",
        deterministic_request="What can you handle",
    ),
    replace(
        CANONICAL_20_CASE_GATE[16],
        case_id="s17_dirty_messages_recoverable",
        tier="supplemental",
        summary="Alternate noisy messaging follow-up.",
        live_request="tell her im here",
        live_hardware_id="live-s17-dirty-messages",
        live_seed_turns=(("I wanna ping Sophia", "What message would you like to send to Sophia?"),),
        classifier_request="tell her im here",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:18:00 UTC\nUSER: I wanna ping Sophia\nASSISTANT: What message would you like to send to Sophia?",
        deterministic_request="tell her im here",
        deterministic_expected_args={"contact": "Sophia", "message": "im here"},
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:18:00 UTC\nUSER: I wanna ping Sophia\nASSISTANT: What message would you like to send to Sophia?",
    ),
    replace(
        CANONICAL_20_CASE_GATE[17],
        case_id="s18_dirty_browser_recoverable",
        tier="supplemental",
        summary="Alternate noisy browser follow-up.",
        live_request="yt ocean noise swap",
        live_hardware_id="live-s18-dirty-browser",
        classifier_request="yt ocean noise swap",
        deterministic_request="yt ocean noise swap",
        deterministic_expected_args={"task": "open youtube and play ocean noise"},
        deterministic_expected_text="Opening YouTube and playing ocean noise.",
    ),
    replace(
        CANONICAL_20_CASE_GATE[18],
        case_id="s19_dirty_search_recoverable",
        tier="supplemental",
        summary="Alternate noisy replace-to-search phrasing.",
        live_request="nah europe headlines instead",
        live_hardware_id="live-s19-dirty-search-pivot",
        live_seed_turns=(("I wanna ping Sophia", "What message would you like to send to Sophia?"),),
        live_expected_text_contains=("europe", "headlines"),
        classifier_request="nah europe headlines instead",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:21:00 UTC\nUSER: I wanna ping Sophia\nASSISTANT: What message would you like to send to Sophia?",
        deterministic_request="nah europe headlines instead",
        deterministic_expected_text="Here are the latest Europe headlines.",
        deterministic_seed_turn="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:21:00 UTC\nUSER: I wanna ping Sophia\nASSISTANT: What message would you like to send to Sophia?",
    ),
    replace(
        CANONICAL_20_CASE_GATE[19],
        case_id="s20_dirty_describe_recoverable",
        tier="supplemental",
        summary="Alternate noisy describe phrasing.",
        live_request="screen rn what is there",
        live_hardware_id="live-s20-dirty-describe",
        classifier_request="screen rn what is there",
        classifier_has_image=False,
        deterministic_request="screen rn what is there",
    ),
)


EXTENDED_40_CASE_GATE: tuple[GoalStackGateCase, ...] = CANONICAL_20_CASE_GATE + SUPPLEMENTAL_20_CASE_GATE
