# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingServiceStub(object):
    """Canonical contract for Nexy voice streaming flows.
    Compatibility:
    - New server + old client: action_message field is optional and skipped silently.
    - New client + old server: client must fall back to legacy <ACTION> parsing and surface "action unavailable".
    - Mixed versions MUST keep using feature flags (actions.open_app.enabled) to gate functionality.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.unary_stream(
                '/streaming.StreamingService/StreamAudio',
                request_serializer=streaming__pb2.StreamRequest.SerializeToString,
                response_deserializer=streaming__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.GenerateWelcomeAudio = channel.unary_stream(
                '/streaming.StreamingService/GenerateWelcomeAudio',
                request_serializer=streaming__pb2.WelcomeRequest.SerializeToString,
                response_deserializer=streaming__pb2.WelcomeResponse.FromString,
                _registered_method=True)
        self.InterruptSession = channel.unary_unary(
                '/streaming.StreamingService/InterruptSession',
                request_serializer=streaming__pb2.InterruptRequest.SerializeToString,
                response_deserializer=streaming__pb2.InterruptResponse.FromString,
                _registered_method=True)
        self.SendMcpActionResult = channel.unary_unary(
                '/streaming.StreamingService/SendMcpActionResult',
                request_serializer=streaming__pb2.McpActionResultRequest.SerializeToString,
                response_deserializer=streaming__pb2.McpActionResultResponse.FromString,
                _registered_method=True)


class StreamingServiceServicer(object):
    """Canonical contract for Nexy voice streaming flows.
    Compatibility:
    - New server + old client: action_message field is optional and skipped silently.
    - New client + old server: client must fall back to legacy <ACTION> parsing and surface "action unavailable".
    - Mixed versions MUST keep using feature flags (actions.open_app.enabled) to gate functionality.

    """

    def StreamAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateWelcomeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterruptSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMcpActionResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=streaming__pb2.StreamRequest.FromString,
                    response_serializer=streaming__pb2.StreamResponse.SerializeToString,
            ),
            'GenerateWelcomeAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateWelcomeAudio,
                    request_deserializer=streaming__pb2.WelcomeRequest.FromString,
                    response_serializer=streaming__pb2.WelcomeResponse.SerializeToString,
            ),
            'InterruptSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InterruptSession,
                    request_deserializer=streaming__pb2.InterruptRequest.FromString,
                    response_serializer=streaming__pb2.InterruptResponse.SerializeToString,
            ),
            'SendMcpActionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMcpActionResult,
                    request_deserializer=streaming__pb2.McpActionResultRequest.FromString,
                    response_serializer=streaming__pb2.McpActionResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """Canonical contract for Nexy voice streaming flows.
    Compatibility:
    - New server + old client: action_message field is optional and skipped silently.
    - New client + old server: client must fall back to legacy <ACTION> parsing and surface "action unavailable".
    - Mixed versions MUST keep using feature flags (actions.open_app.enabled) to gate functionality.

    """

    @staticmethod
    def StreamAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streaming.StreamingService/StreamAudio',
            streaming__pb2.StreamRequest.SerializeToString,
            streaming__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateWelcomeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streaming.StreamingService/GenerateWelcomeAudio',
            streaming__pb2.WelcomeRequest.SerializeToString,
            streaming__pb2.WelcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InterruptSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/InterruptSession',
            streaming__pb2.InterruptRequest.SerializeToString,
            streaming__pb2.InterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMcpActionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/SendMcpActionResult',
            streaming__pb2.McpActionResultRequest.SerializeToString,
            streaming__pb2.McpActionResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
