#!/bin/bash
# Настройка алёртов по логам (PR-7)
# Примеры команд для настройки мониторинга

LOG_FILE="${1:-server.log}"

echo "📊 Настройка алёртов по логам"
echo "=============================="
echo "Лог файл: $LOG_FILE"
echo "=============================="
echo ""

# 1. p95 latency > 1000ms (warn), >1500ms (page)
echo "1. Алёрт на p95 latency:"
echo ""
echo "   # Warn при p95 > 1000ms"
echo "   p95=\$(grep -E 'dur_ms=[0-9]+.*method=StreamAudio' $LOG_FILE | tail -100 | grep -oE 'dur_ms=([0-9]+)' | cut -d= -f2 | sort -n | awk '{latencies[NR]=\$1} END {n=length(latencies); if (n>0) {p95_idx=int(n*0.95); if (p95_idx==0) p95_idx=1; print latencies[p95_idx]} else print \"0\"}')"
echo "   if [ \"\$p95\" -gt 1000 ]; then"
echo "       echo \"⚠️ WARN: p95 latency превышен: \${p95}ms\""
echo "   fi"
echo ""
echo "   # Page при p95 > 1500ms"
echo "   if [ \"\$p95\" -gt 1500 ]; then"
echo "       echo \"🚨 PAGE: p95 latency критичен: \${p95}ms\""
echo "       # Отправить уведомление (email, Slack, PagerDuty и т.д.)"
echo "   fi"
echo ""

# 2. error-rate > 5% (warn), >10% (page)
echo "2. Алёрт на error rate:"
echo ""
echo "   # Расчет error rate"
echo "   total=\$(grep -c 'scope=grpc method=StreamAudio' $LOG_FILE | tail -100 || echo \"0\")"
echo "   errors=\$(grep -c 'decision=error.*method=StreamAudio' $LOG_FILE | tail -100 || echo \"0\")"
echo "   if [ \"\$total\" -gt 0 ]; then"
echo "       error_rate=\$(echo \"scale=2; \$errors * 100 / \$total\" | bc)"
echo "       echo \"Error rate: \${error_rate}%\""
echo ""
echo "       # Warn при error rate > 5%"
echo "       if [ \$(echo \"\$error_rate > 5\" | bc) -eq 1 ]; then"
echo "           echo \"⚠️ WARN: Error rate превышен: \${error_rate}%\""
echo "       fi"
echo ""
echo "       # Page при error rate > 10%"
echo "       if [ \$(echo \"\$error_rate > 10\" | bc) -eq 1 ]; then"
echo "           echo \"🚨 PAGE: Error rate критичен: \${error_rate}%\""
echo "           # Отправить уведомление"
echo "       fi"
echo "   fi"
echo ""

# 3. Рост unavailable/retry/abort в ×2 от медианы за 24ч
echo "3. Алёрт на рост unavailable/retry/abort:"
echo ""
echo "   # Базовая линия за последние 24 часа"
echo "   baseline=\$(grep -c 'decision=(retry|abort).*unavailable' $LOG_FILE | head -1000 || echo \"0\")"
echo ""
echo "   # Текущее значение (последние 100 записей)"
echo "   current=\$(grep -c 'decision=(retry|abort).*unavailable' $LOG_FILE | tail -100 || echo \"0\")"
echo ""
echo "   # Расчет медианы"
echo "   if [ \"\$baseline\" -gt 0 ]; then"
echo "       median=\$(echo \"\$baseline / 2\" | bc)"
echo "       threshold=\$(echo \"\$median * 2\" | bc)"
echo ""
echo "       if [ \"\$current\" -gt \"\$threshold\" ]; then"
echo "           echo \"🚨 PAGE: Рост unavailable/retry/abort: \$current > \$threshold (×2 от медианы)\""
echo "           # Отправить уведомление"
echo "       fi"
echo "   fi"
echo ""

# 4. Пример для cron (каждые 5 минут)
echo "4. Пример cron задачи (каждые 5 минут):"
echo ""
echo "   */5 * * * * /path/to/scripts/setup_alerts.sh /path/to/server.log >> /var/log/nexy-alerts.log 2>&1"
echo ""

# 5. Пример для systemd timer
echo "5. Пример systemd timer:"
echo ""
echo "   # /etc/systemd/system/nexy-alerts.timer"
echo "   [Unit]"
echo "   Description=Nexy Alerts Timer"
echo ""
echo "   [Timer]"
echo "   OnCalendar=*:0/5"
echo "   Persistent=true"
echo ""
echo "   [Install]"
echo "   WantedBy=timers.target"
echo ""
echo "   # /etc/systemd/system/nexy-alerts.service"
echo "   [Unit]"
echo "   Description=Nexy Alerts Check"
echo ""
echo "   [Service]"
echo "   Type=oneshot"
echo "   ExecStart=/path/to/scripts/setup_alerts.sh /path/to/server.log"
echo ""

echo "=============================="
echo "💡 Подсказки:"
echo "   - Настройте интеграцию с вашей системой мониторинга (Prometheus, CloudWatch, Datadog и т.д.)"
echo "   - Используйте структурированные логи для автоматического извлечения метрик"
echo "   - Настройте уведомления (email, Slack, PagerDuty и т.д.)"
echo ""

