from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple


@dataclass(frozen=True)
class GoalStackGateCase:
    case_id: str
    tier: str
    transition_type: str
    category: str
    prompt_style: str
    paired: bool
    owner_focus: Tuple[str, ...]
    summary: str
    live_request: Optional[str] = None
    live_expected_route: Optional[str] = None
    live_expected_command: Optional[str] = None
    live_expected_text_contains: Tuple[str, ...] = ()
    live_expected_goal_state: Optional[str] = None
    live_hardware_id: Optional[str] = None
    live_seed_turns: Tuple[Tuple[str, str], ...] = ()
    classifier_request: Optional[str] = None
    classifier_expected_route: Optional[str] = None
    classifier_runtime_current_goal: Optional[str] = None
    classifier_runtime_short_term: Optional[str] = None
    classifier_has_image: bool = False


CANONICAL_20_CASE_GATE: tuple[GoalStackGateCase, ...] = (
    GoalStackGateCase(
        "g01_messages_start",
        "core",
        "new_task",
        "messages",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Start Messages clarification chain with explicit recipient.",
        live_request="Send a message to Sophia",
        live_expected_route="messages",
        live_expected_text_contains=("Sophia",),
        live_expected_goal_state="set",
        live_hardware_id="live-g01-messages",
        classifier_request="send a message to Sophia",
        classifier_expected_route="messages",
    ),
    GoalStackGateCase(
        "g02_messages_followup_pronoun",
        "core",
        "pronoun_continuation",
        "messages",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Continue active Messages chain with pronoun payload reuse.",
        live_request="Tell her I will be late",
        live_expected_route="messages",
        live_expected_command="send_message",
        live_expected_text_contains=("Sending", "Sophia"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g01-messages",
        classifier_request="tell her how are you doing today",
        classifier_expected_route="messages",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:32:39 UTC\nUSER: send a message to Sophia\nASSISTANT: What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g03_whatsapp_start",
        "core",
        "new_task",
        "whatsapp",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Start WhatsApp clarification chain.",
        live_request="Send a WhatsApp message to Mom",
        live_expected_route="whatsapp",
        live_expected_text_contains=("Mom",),
        live_expected_goal_state="set",
        live_hardware_id="live-g03-whatsapp",
        classifier_request="send a WhatsApp message to Mom",
        classifier_expected_route="whatsapp",
    ),
    GoalStackGateCase(
        "g04_whatsapp_followup",
        "core",
        "continuation_completion",
        "whatsapp",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Finish WhatsApp chain with known contact reuse.",
        live_request="Tell Mom I arrived",
        live_expected_route="whatsapp",
        live_expected_command="send_whatsapp_message",
        live_expected_text_contains=("Mom",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g03-whatsapp",
        classifier_request="continue",
        classifier_expected_route="whatsapp",
        classifier_runtime_current_goal="User wants to send a WhatsApp message to Mom. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:40:00 UTC\nUSER: send a WhatsApp message to Mom\nASSISTANT: What message do you want to send to Mom?",
    ),
    GoalStackGateCase(
        "g05_browser_direct",
        "core",
        "same_turn_completion",
        "browser",
        "clean",
        False,
        ("memory", "classifier", "generator", "live"),
        "Direct browser action without clarification.",
        live_request="Open YouTube and play jazz",
        live_expected_route="browser",
        live_expected_command="browser_use",
        live_expected_text_contains=("YouTube",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g05-browser",
        classifier_request="open YouTube and play jazz",
        classifier_expected_route="browser",
    ),
    GoalStackGateCase(
        "g06_browser_followup_short",
        "core",
        "short_continuation",
        "browser",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Continue browser chain with short target phrase.",
        live_request="sleep music instead",
        live_expected_route="browser",
        live_expected_command="browser_use",
        live_expected_text_contains=("sleep",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g06-browser-followup",
        live_seed_turns=(("Open YouTube and find sleep music", "What should I find on YouTube?"),),
        classifier_request="rain sounds",
        classifier_expected_route="browser",
        classifier_runtime_current_goal="User wants to search YouTube. Missing detail: search query.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:35:00 UTC\nUSER: open YouTube and find\nASSISTANT: What should I find on YouTube?",
    ),
    GoalStackGateCase(
        "g07_search_direct",
        "core",
        "same_turn_completion",
        "google_search",
        "clean",
        False,
        ("memory", "classifier", "generator", "live"),
        "Direct factual search answered in the same turn.",
        live_request="Find latest world news",
        live_expected_route="google_search",
        live_expected_text_contains=("world", "news"),
        live_expected_goal_state="empty",
        live_hardware_id="live-g07-search",
        classifier_request="find latest world news",
        classifier_expected_route="google_search",
    ),
    GoalStackGateCase(
        "g08_search_followup_topic",
        "core",
        "continuation_completion",
        "google_search",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Resolve search topic after clarification.",
        live_request="world news",
        live_expected_route="google_search",
        live_expected_text_contains=("world", "news"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g08-search-followup",
        live_seed_turns=(("Find news", "What kind of news do you want?"),),
        classifier_request="world news",
        classifier_expected_route="google_search",
        classifier_runtime_current_goal="User wants news. Missing detail: topic.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:36:00 UTC\nUSER: find news\nASSISTANT: What kind of news do you want?",
    ),
    GoalStackGateCase(
        "g09_system_direct",
        "core",
        "same_turn_completion",
        "system_control",
        "clean",
        False,
        ("memory", "classifier", "generator", "live"),
        "Open desktop app directly.",
        live_request="Open Safari",
        live_expected_route="system_control",
        live_expected_command="open_app",
        live_expected_text_contains=("Safari",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g09-system",
        classifier_request="open Safari",
        classifier_expected_route="system_control",
    ),
    GoalStackGateCase(
        "g10_system_clarify_start",
        "core",
        "new_task",
        "system_control",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Start app-open clarification when app name is missing.",
        live_request="Open an app",
        live_expected_route="system_control",
        live_expected_text_contains=("open",),
        live_expected_goal_state="set",
        live_hardware_id="live-g10-system-clarify",
        classifier_request="open",
        classifier_expected_route="none",
    ),
    GoalStackGateCase(
        "g11_system_followup_target",
        "core",
        "continuation_completion",
        "system_control",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Resolve missing app slot and execute.",
        live_request="Safari",
        live_expected_route="system_control",
        live_expected_command="open_app",
        live_expected_text_contains=("Safari",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g10-system-clarify",
        classifier_request="Safari",
        classifier_expected_route="system_control",
        classifier_runtime_current_goal="User wants to open an app. Missing detail: app name.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:37:00 UTC\nUSER: open\nASSISTANT: What app do you want to open?",
    ),
    GoalStackGateCase(
        "g12_cancel_old_task",
        "core",
        "cancel",
        "none",
        "clean",
        True,
        ("memory", "classifier", "live"),
        "Cancel an active task without starting a new one.",
        live_request="No, never mind",
        live_expected_route="none",
        live_expected_text_contains=("okay",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g12-cancel",
        live_seed_turns=(("Send a message to Sophia", "What message would you like to send to Sophia?"),),
        classifier_request="no, I do not want to send a message",
        classifier_expected_route="none",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:10:00 UTC\nUSER: send a message to Sophia\nASSISTANT: What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g13_replace_message_to_app",
        "core",
        "replace",
        "system_control",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Replace active messaging task with app open.",
        live_request="No, open Safari instead",
        live_expected_route="system_control",
        live_expected_command="open_app",
        live_expected_text_contains=("Opening", "Safari"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g13-replace-app",
        live_seed_turns=(("Send a message to Sophia", "What message would you like to send to Sophia?"),),
        classifier_request="no, open Safari instead",
        classifier_expected_route="system_control",
        classifier_runtime_current_goal="User wants to send a message to Sophia. Missing detail: message text.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:12:00 UTC\nUSER: send a message to Sophia\nASSISTANT: What message would you like to send to Sophia?",
    ),
    GoalStackGateCase(
        "g14_replace_browser_to_message",
        "core",
        "replace",
        "messages",
        "clean",
        True,
        ("memory", "classifier", "generator", "live"),
        "Replace active browser task with Messages task.",
        live_request="No, send a message to Sophia instead",
        live_expected_route="messages",
        live_expected_text_contains=("Sophia",),
        live_expected_goal_state="set",
        live_hardware_id="live-g14-replace-message",
        live_seed_turns=(("Open YouTube and find", "What should I find on YouTube?"),),
        classifier_request="no, send a message to Sophia instead",
        classifier_expected_route="messages",
        classifier_runtime_current_goal="User wants to search YouTube. Missing detail: search query.",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 02:16:00 UTC\nUSER: open YouTube and find\nASSISTANT: What should I find on YouTube?",
    ),
    GoalStackGateCase(
        "g15_casual_none",
        "core",
        "no_task",
        "none",
        "clean",
        False,
        ("memory", "classifier", "live"),
        "Ordinary conversation must not create a goal.",
        live_request="How are you?",
        live_expected_route="none",
        live_expected_text_contains=("doing",),
        live_expected_goal_state="empty",
        live_hardware_id="live-g15-casual",
        classifier_request="what did I ask before",
        classifier_expected_route="none",
    ),
    GoalStackGateCase(
        "g16_capability_direct",
        "core",
        "no_task",
        "capability",
        "clean",
        False,
        ("memory", "classifier", "live"),
        "Capability request must stay outside executable lifecycle.",
        live_request="What can you do?",
        live_expected_route="capability",
        live_expected_text_contains=("help",),
        live_expected_goal_state="empty",
        live_hardware_id="live-g16-capability",
        classifier_request="what can you do",
        classifier_expected_route="capability",
    ),
    GoalStackGateCase(
        "g17_dirty_messages_recoverable",
        "rotatable",
        "same_turn_completion",
        "messages",
        "dirty",
        False,
        ("classifier", "generator", "live"),
        "Recover noisy Messages request and still emit action payload.",
        live_request="snd mesage to sofiya how r u",
        live_expected_route="messages",
        live_expected_command="send_message",
        live_expected_text_contains=("Sending",),
        live_expected_goal_state="clear",
        live_hardware_id="live-g17-dirty-messages",
        classifier_request="yes",
        classifier_expected_route="google_search",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:38:00 UTC\nUSER: find latest bitcoin price\nASSISTANT: Do you want me to search for the latest bitcoin price now?",
    ),
    GoalStackGateCase(
        "g18_dirty_browser_recoverable",
        "rotatable",
        "same_turn_completion",
        "browser",
        "dirty",
        False,
        ("classifier", "generator", "live"),
        "Recover noisy browser intent and route correctly.",
        live_request="opn yotube n ply lofi",
        live_expected_route="browser",
        live_expected_command="browser_use",
        live_expected_text_contains=("YouTube", "lofi"),
        live_expected_goal_state="clear",
        live_hardware_id="live-g18-dirty-browser",
        classifier_request="yes",
        classifier_expected_route="browser",
        classifier_runtime_short_term="CURRENT_TURN:\nTIME_UTC: 2026-03-07 01:39:00 UTC\nUSER: open YouTube and play jazz\nASSISTANT: Do you want me to open YouTube now?",
    ),
    GoalStackGateCase(
        "g19_dirty_search_recoverable",
        "rotatable",
        "same_turn_completion",
        "google_search",
        "dirty",
        False,
        ("classifier", "live"),
        "Recover noisy search query and answer as factual search.",
        live_request="lost news",
        live_expected_route="google_search",
        live_expected_text_contains=("news",),
        live_expected_goal_state="empty",
        live_hardware_id="live-g19-dirty-search",
        classifier_request="upgrade my subscription",
        classifier_expected_route="payment",
    ),
    GoalStackGateCase(
        "g20_dirty_describe_recoverable",
        "rotatable",
        "same_turn_completion",
        "describe",
        "dirty",
        False,
        ("classifier", "generator", "live"),
        "Recover noisy describe request and stay on describe route.",
        live_request="deskribe my scren",
        live_expected_route="describe",
        live_expected_text_contains=("screen",),
        live_expected_goal_state="empty",
        live_hardware_id="live-g20-dirty-describe",
        classifier_request="",
        classifier_expected_route="describe",
        classifier_has_image=True,
    ),
)
